package com.andrewnguyen.bowpress.core.model

import kotlin.math.abs
import kotlin.math.sqrt

/**
 * A suggested sight mark generated by interpolating from the archer's
 * existing measured marks. Mirrors iOS `SightMarkSuggestion`
 * (Analytics/SightMarkSuggester.swift). RSE is 0 with exactly 3 marks (fit
 * is exactly determined) and grows as input marks deviate from the
 * best-fit curve.
 */
data class SightMarkSuggestion(
    val distance: Double,
    val distanceUnit: DistanceUnit,
    val mark: Double,
    val residualStandardError: Double,
    val sourceMarkCount: Int,
)

/**
 * Quadratic least-squares interpolation of sight marks. The fit is honest
 * for interpolation within the marked range and a small extrapolation
 * buffer; we deliberately refuse to extrapolate further because polynomial
 * fits diverge fast outside their support.
 *
 * 1:1 port of iOS [SightMarkSuggester] (185 LOC) — same constants, same
 * gating rules, same Gaussian elimination with partial pivoting.
 */
object SightMarkSuggester {

    // ── Tuning ──────────────────────────────────────────────────────

    /** Industry consensus: minimum 3 marks for any kind of curve fit. */
    const val MIN_MARK_COUNT = 3

    /**
     * Minimum max-min distance spread between input marks. Industry
     * guidance is "20 yards apart" (Precision Cut Archery).
     */
    val MIN_SPREAD_METERS: Double = 20.0 * DistanceUnit.YARDS.metersPerUnit

    /**
     * How far past the marked range we'll still suggest. Polynomial
     * extrapolation diverges fast, so we cap to a small buffer.
     */
    val EXTRAPOLATION_BUFFER_METERS: Double = 5.0 * DistanceUnit.YARDS.metersPerUnit

    // ── Outcomes ────────────────────────────────────────────────────

    sealed class Outcome {
        data class Suggested(val suggestion: SightMarkSuggestion) : Outcome()
        data class NotEnoughMarks(val have: Int) : Outcome()
        data class SpreadTooSmall(val haveMeters: Double) : Outcome()
        data class DistanceOutOfRange(val haveMinMeters: Double, val haveMaxMeters: Double) : Outcome()
    }

    /**
     * Returns a suggestion for [distance] (interpreted in [unit]) given
     * the archer's measured marks. [marks] should already be scoped to
     * a single bow — this function does not filter by bowId. Synthesized
     * (`isSuggestion = true`) marks are filtered out before fitting so
     * we never compound past suggestions.
     */
    fun suggest(
        atDistance: Double,
        unit: DistanceUnit,
        from: List<SightMark>,
    ): Outcome {
        val measured = from.filter { !it.isSuggestion }
        if (measured.size < MIN_MARK_COUNT) {
            return Outcome.NotEnoughMarks(measured.size)
        }
        val xs = measured.map { it.distanceInMeters }
        val ys = measured.map { it.mark }
        val minX = xs.min()
        val maxX = xs.max()
        val spread = maxX - minX
        if (spread < MIN_SPREAD_METERS) {
            return Outcome.SpreadTooSmall(spread)
        }
        val targetMeters = atDistance * unit.metersPerUnit
        val lower = minX - EXTRAPOLATION_BUFFER_METERS
        val upper = maxX + EXTRAPOLATION_BUFFER_METERS
        if (targetMeters < lower || targetMeters > upper) {
            return Outcome.DistanceOutOfRange(minX, maxX)
        }

        val coeffs = quadraticLeastSquares(xs, ys)
            ?: return Outcome.SpreadTooSmall(spread)
        val (a, b, c) = coeffs

        val predicted = a + b * targetMeters + c * targetMeters * targetMeters

        val residuals = xs.zip(ys).map { (x, y) ->
            val yhat = a + b * x + c * x * x
            y - yhat
        }
        val ssr = residuals.sumOf { it * it }
        val dof = maxOf(1, measured.size - 3)
        val rse = if (measured.size == 3) 0.0 else sqrt(ssr / dof.toDouble())

        return Outcome.Suggested(
            SightMarkSuggestion(
                distance = atDistance,
                distanceUnit = unit,
                mark = predicted,
                residualStandardError = rse,
                sourceMarkCount = measured.size,
            ),
        )
    }

    /**
     * Solves `y = a + b·x + c·x²` in least-squares sense. Returns
     * `null` when the normal-equation matrix is numerically singular.
     */
    internal fun quadraticLeastSquares(
        xs: List<Double>,
        ys: List<Double>,
    ): Triple<Double, Double, Double>? {
        require(xs.size == ys.size)
        val n = xs.size.toDouble()
        var sx = 0.0; var sx2 = 0.0; var sx3 = 0.0; var sx4 = 0.0
        var sy = 0.0; var sxy = 0.0; var sx2y = 0.0
        for (i in xs.indices) {
            val x = xs[i]
            val y = ys[i]
            val x2 = x * x
            val x3 = x2 * x
            val x4 = x2 * x2
            sx += x; sx2 += x2; sx3 += x3; sx4 += x4
            sy += y; sxy += x * y; sx2y += x2 * y
        }
        // Normal equations:
        //   [ n   sx   sx2 ] [a]   [sy   ]
        //   [ sx  sx2  sx3 ] [b] = [sxy  ]
        //   [ sx2 sx3  sx4 ] [c]   [sx2y ]
        val matrix = Array(3) { DoubleArray(3) }
        matrix[0][0] = n;   matrix[0][1] = sx;  matrix[0][2] = sx2
        matrix[1][0] = sx;  matrix[1][1] = sx2; matrix[1][2] = sx3
        matrix[2][0] = sx2; matrix[2][1] = sx3; matrix[2][2] = sx4
        val rhs = doubleArrayOf(sy, sxy, sx2y)
        if (!solve3x3(matrix, rhs)) return null
        return Triple(rhs[0], rhs[1], rhs[2])
    }

    /**
     * Gaussian elimination with partial pivoting on a 3×3 system.
     * [matrix] and [rhs] are mutated; on success [rhs] holds the solution.
     * Returns false if the system is numerically singular.
     */
    private fun solve3x3(matrix: Array<DoubleArray>, rhs: DoubleArray): Boolean {
        for (i in 0..2) {
            var pivotRow = i
            var pivotVal = abs(matrix[i][i])
            for (k in (i + 1)..2) {
                if (abs(matrix[k][i]) > pivotVal) {
                    pivotVal = abs(matrix[k][i])
                    pivotRow = k
                }
            }
            if (pivotVal < 1e-12) return false
            if (pivotRow != i) {
                val tmp = matrix[i]; matrix[i] = matrix[pivotRow]; matrix[pivotRow] = tmp
                val r = rhs[i]; rhs[i] = rhs[pivotRow]; rhs[pivotRow] = r
            }
            for (k in (i + 1)..2) {
                val factor = matrix[k][i] / matrix[i][i]
                for (j in i..2) matrix[k][j] -= factor * matrix[i][j]
                rhs[k] -= factor * rhs[i]
            }
        }
        for (i in 2 downTo 0) {
            var s = rhs[i]
            if (i < 2) for (j in (i + 1)..2) s -= matrix[i][j] * rhs[j]
            rhs[i] = s / matrix[i][i]
        }
        return true
    }
}
